### ISSUE TITLE
Make offline coloring of the circle accesible

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/Site#2094]
### What happened?

When going offline the only difference is between red and green, which is not an accessible solution for color blind people

### What steps will reproduce the bug?

1. Go offline
2. Look at the circle on the right top corner

### What I expect to happen

There should be another indication besides changing color

### Platform

- [X] Israel Hiking Map app
- [X] Israel Hiking Map site in a browser

### OS Name and Version

Any

### Browser Name and Version

Any

### Additional information

The following css line can be added I believe:
```css
.circle-line {
    position: absolute;
    top: 6px;
    left: 1px;
    border: solid white 1px;
    font-size: 8px;
    color: #fff;
    line-height: normal;
    z-index: 3;
    display: flex;
    justify-content: center;
    width: 10px;
    transform: rotate(-45deg);
}
```
